# stage 1: build the frontend
FROM node:18-alpine as builder

WORKDIR /app

COPY frontend-vue/package.json .
COPY frontend-vue/package-lock.json .

RUN npm install

COPY frontend-vue/ .

RUN npm run build

# stage 2: serve the frontend with nginx
FROM nginx:stable-alpine

COPY --from=builder /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
